### ISSUE TITLE
Bootstrapping doesn't happen properly on migration commands

### ISSUE THREAD

**Issue by sivanbecker** [getweber/cob#8]
When i update a new package in deps (cob-project.yml) and run testserver ,the package is installed under the test venv but it should also be installed in the working env as it is needed for migration etc..

**Comment by vmalloc** [comment]
By working env do you mean ``.cob/env``? Otherwise cob does not attempt to install anything on the host system, and it should not be necessary for migrations (cob switches to the internal env to do the migrations). If you can describe a specific situation where this is needed, we will fix it

**Comment by sivanbecker** [comment]
ok so this is what i had - my models use sqlalchemy-utils (from sqlalchemy_utils import IPAddressType). when creating a new revision or migrating up, this package is needed. 
1. When running migrate init ,the mako file is created amongst other files and in it sqlalchemy is imported as "sa". if i also had the utils ,then all revision file would be ok. should manually add this import to revision files ? 
2. Even if i have the import statement in my revision file, when migrating up ,not having the package installed , fails the process.

hope its clear enough.

**Comment by vmalloc** [comment]
Ok, so the answer to the first question is that you need to import stuff you need in the migration script. It doesn't get imported automatically.

The second part is that we need to add a `pip_requirements` section to the project config, so that these deps be automatically installed inside the environment. I opened #9 for this
